### ISSUE TITLE
are operations on integers in scope for this library?

### ISSUE THREAD

**Issue by 3b** [sharplispers/nibbles#7]
It would be nice to have fast endian swap, signed<->unsigned, unsigned<->float,  etc. operations for various sizes of integers for cases where they can't be done while reading from an octet vector (for example when parsing data that isn't byte-aligned).

Is that something that would be reasonable to add to nibbles, or would it be better as a separate library?

**Comment by brown** [comment]
Nibbles seems to be in maintenance mode at this point and all the current code works on byte-aligned data.  I think a new library probably makes the most sense.
