### ISSUE TITLE
read/write 'native' endian

### ISSUE THREAD

**Issue by 3b** [sharplispers/nibbles#8]
Would be nice to have an alias for readers/writers that used the native endianness of the system rather than specifying big or little endian, either for cases where data is known to match system, or for cases where it doesn't matter like copying multiple bytes at a time.

**Comment by brown** [comment]
I'm not sure native endian getters and setters are really useful as a part of nibbles.  Luckily, a user of nibbles can easily define them or just use the routines that match the endianness of the platform the code is running on.
